# Generated by Django 4.2 on 2024-10-05 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 12, 32, 11, 896317, tzinfo=datetime.timezone.utc)),
        ),
    ]
